language: node_js
node_js:
  - 8.10
cache: yarn
install:
  - yarn
  - yarn flow-typed
script:
  - yarn test
  - yarn build
before_deploy:
  - yarn global add serverless
deploy:
  provider: script
  script: sls deploy
